package edu.amikom.perpus.domain;
// Generated May 19, 2019 11:22:43 PM by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Administrator generated by hbm2java
 */
@Entity
@Table(name="administrator")
public class Administrator  implements java.io.Serializable {


     private String nip;
     private String agama;
     private String alamat;
     private String email;
     private boolean jenisKelamin;
     private String nama;
     private String noTelepon;
     private String password;

    public Administrator() {
    }

    public Administrator(String nip, String agama, String alamat, String email, boolean jenisKelamin, String nama, String noTelepon, String password) {
       this.nip = nip;
       this.agama = agama;
       this.alamat = alamat;
       this.email = email;
       this.jenisKelamin = jenisKelamin;
       this.nama = nama;
       this.noTelepon = noTelepon;
       this.password = password;
    }
   
     @Id 

    
    @Column(name="nip", unique=true, length=20)
    public String getNip() {
        return this.nip;
    }
    
    public void setNip(String nip) {
        this.nip = nip;
    }

    
    @Column(name="agama", length=20)
    public String getAgama() {
        return this.agama;
    }
    
    public void setAgama(String agama) {
        this.agama = agama;
    }

    
    @Column(name="alamat")
    public String getAlamat() {
        return this.alamat;
    }
    
    public void setAlamat(String alamat) {
        this.alamat = alamat;
    }

    
    @Column(name="email", length=100)
    public String getEmail() {
        return this.email;
    }
    
    public void setEmail(String email) {
        this.email = email;
    }

    
    @Column(name="jenis_kelamin")
    public boolean isJenisKelamin() {
        return this.jenisKelamin;
    }
    
    public void setJenisKelamin(boolean jenisKelamin) {
        this.jenisKelamin = jenisKelamin;
    }

    
    @Column(name="nama", length=100)
    public String getNama() {
        return this.nama;
    }
    
    public void setNama(String nama) {
        this.nama = nama;
    }

    
    @Column(name="no_telepon", length=20)
    public String getNoTelepon() {
        return this.noTelepon;
    }
    
    public void setNoTelepon(String noTelepon) {
        this.noTelepon = noTelepon;
    }

    
    @Column(name="password", length=200)
    public String getPassword() {
        return this.password;
    }
    
    public void setPassword(String password) {
        this.password = password;
    }




}


