package edu.amikom.perpus.domain;
// Generated May 19, 2019 11:22:43 PM by Hibernate Tools 4.3.1


import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.UniqueConstraint;

/**
 * DetailTransaksi generated by hbm2java
 */
@Entity
@Table(name="detail_transaksi", uniqueConstraints = @UniqueConstraint(columnNames="id_buku") 
)
public class DetailTransaksi  implements java.io.Serializable {


     private Integer idDetailTansaksi;
     private Buku buku;
     private Transaksi transaksi;
     private String keterangan;
     private Date tanggalPengembalian;

    public DetailTransaksi() {
    }

    public DetailTransaksi(Buku buku, Transaksi transaksi, String keterangan, Date tanggalPengembalian) {
       this.buku = buku;
       this.transaksi = transaksi;
       this.keterangan = keterangan;
       this.tanggalPengembalian = tanggalPengembalian;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="id_detail_tansaksi", unique=true)
    public Integer getIdDetailTansaksi() {
        return this.idDetailTansaksi;
    }
    
    public void setIdDetailTansaksi(Integer idDetailTansaksi) {
        this.idDetailTansaksi = idDetailTansaksi;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="id_buku", unique=true)
    public Buku getBuku() {
        return this.buku;
    }
    
    public void setBuku(Buku buku) {
        this.buku = buku;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="id_transaksi")
    public Transaksi getTransaksi() {
        return this.transaksi;
    }
    
    public void setTransaksi(Transaksi transaksi) {
        this.transaksi = transaksi;
    }

    
    @Column(name="keterangan")
    public String getKeterangan() {
        return this.keterangan;
    }
    
    public void setKeterangan(String keterangan) {
        this.keterangan = keterangan;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="tanggal_pengembalian", length=19)
    public Date getTanggalPengembalian() {
        return this.tanggalPengembalian;
    }
    
    public void setTanggalPengembalian(Date tanggalPengembalian) {
        this.tanggalPengembalian = tanggalPengembalian;
    }




}


