package edu.amikom.perpus.domain;
// Generated May 19, 2019 11:22:43 PM by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Mahasiswa generated by hbm2java
 */
@Entity
@Table(name="mahasiswa")
public class Mahasiswa  implements java.io.Serializable {


     private String nim;
     private String agama;
     private String alamat;
     private String email;
     private boolean jenisKelamin;
     private String nama;
     private String noTelepon;
     private Date tanggalDiterima;
     private Date tanggalRegistrasi;
     private Set<Transaksi> transaksis = new HashSet<Transaksi>(0);

    public Mahasiswa() {
    }

	
    public Mahasiswa(String nim, String agama, String alamat, String email, boolean jenisKelamin, String nama, String noTelepon, Date tanggalDiterima, Date tanggalRegistrasi) {
        this.nim = nim;
        this.agama = agama;
        this.alamat = alamat;
        this.email = email;
        this.jenisKelamin = jenisKelamin;
        this.nama = nama;
        this.noTelepon = noTelepon;
        this.tanggalDiterima = tanggalDiterima;
        this.tanggalRegistrasi = tanggalRegistrasi;
    }
    public Mahasiswa(String nim, String agama, String alamat, String email, boolean jenisKelamin, String nama, String noTelepon, Date tanggalDiterima, Date tanggalRegistrasi, Set<Transaksi> transaksis) {
       this.nim = nim;
       this.agama = agama;
       this.alamat = alamat;
       this.email = email;
       this.jenisKelamin = jenisKelamin;
       this.nama = nama;
       this.noTelepon = noTelepon;
       this.tanggalDiterima = tanggalDiterima;
       this.tanggalRegistrasi = tanggalRegistrasi;
       this.transaksis = transaksis;
    }
   
     @Id 

    
    @Column(name="nim", unique=true, length=15)
    public String getNim() {
        return this.nim;
    }
    
    public void setNim(String nim) {
        this.nim = nim;
    }

    
    @Column(name="agama", length=20)
    public String getAgama() {
        return this.agama;
    }
    
    public void setAgama(String agama) {
        this.agama = agama;
    }

    
    @Column(name="alamat")
    public String getAlamat() {
        return this.alamat;
    }
    
    public void setAlamat(String alamat) {
        this.alamat = alamat;
    }

    
    @Column(name="email", length=100)
    public String getEmail() {
        return this.email;
    }
    
    public void setEmail(String email) {
        this.email = email;
    }

    
    @Column(name="jenis_kelamin")
    public boolean isJenisKelamin() {
        return this.jenisKelamin;
    }
    
    public void setJenisKelamin(boolean jenisKelamin) {
        this.jenisKelamin = jenisKelamin;
    }

    
    @Column(name="nama", length=200)
    public String getNama() {
        return this.nama;
    }
    
    public void setNama(String nama) {
        this.nama = nama;
    }

    
    @Column(name="no_telepon", length=20)
    public String getNoTelepon() {
        return this.noTelepon;
    }
    
    public void setNoTelepon(String noTelepon) {
        this.noTelepon = noTelepon;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="tanggal_diterima", length=19)
    public Date getTanggalDiterima() {
        return this.tanggalDiterima;
    }
    
    public void setTanggalDiterima(Date tanggalDiterima) {
        this.tanggalDiterima = tanggalDiterima;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="tanggal_registrasi", length=19)
    public Date getTanggalRegistrasi() {
        return this.tanggalRegistrasi;
    }
    
    public void setTanggalRegistrasi(Date tanggalRegistrasi) {
        this.tanggalRegistrasi = tanggalRegistrasi;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="mahasiswa")
    public Set<Transaksi> getTransaksis() {
        return this.transaksis;
    }
    
    public void setTransaksis(Set<Transaksi> transaksis) {
        this.transaksis = transaksis;
    }




}


