package edu.amikom.perpus.domain;
// Generated May 19, 2019 11:22:43 PM by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Petugas generated by hbm2java
 */
@Entity
@Table(name="petugas")
public class Petugas  implements java.io.Serializable {


     private String nip;
     private String agama;
     private String alamat;
     private String email;
     private boolean jenisKelamin;
     private String nama;
     private String noTelepon;
     private String password;
     private boolean statusAktif;
     private Date tanggalKeluar;
     private Date tanggalMasuk;
     private Set<Transaksi> transaksis = new HashSet<Transaksi>(0);

    public Petugas() {
    }

	
    public Petugas(String nip, String agama, String alamat, String email, boolean jenisKelamin, String nama, String noTelepon, String password, boolean statusAktif, Date tanggalKeluar, Date tanggalMasuk) {
        this.nip = nip;
        this.agama = agama;
        this.alamat = alamat;
        this.email = email;
        this.jenisKelamin = jenisKelamin;
        this.nama = nama;
        this.noTelepon = noTelepon;
        this.password = password;
        this.statusAktif = statusAktif;
        this.tanggalKeluar = tanggalKeluar;
        this.tanggalMasuk = tanggalMasuk;
    }
    public Petugas(String nip, String agama, String alamat, String email, boolean jenisKelamin, String nama, String noTelepon, String password, boolean statusAktif, Date tanggalKeluar, Date tanggalMasuk, Set<Transaksi> transaksis) {
       this.nip = nip;
       this.agama = agama;
       this.alamat = alamat;
       this.email = email;
       this.jenisKelamin = jenisKelamin;
       this.nama = nama;
       this.noTelepon = noTelepon;
       this.password = password;
       this.statusAktif = statusAktif;
       this.tanggalKeluar = tanggalKeluar;
       this.tanggalMasuk = tanggalMasuk;
       this.transaksis = transaksis;
    }
   
     @Id 

    
    @Column(name="nip", unique=true, length=20)
    public String getNip() {
        return this.nip;
    }
    
    public void setNip(String nip) {
        this.nip = nip;
    }

    
    @Column(name="agama", length=20)
    public String getAgama() {
        return this.agama;
    }
    
    public void setAgama(String agama) {
        this.agama = agama;
    }

    
    @Column(name="alamat")
    public String getAlamat() {
        return this.alamat;
    }
    
    public void setAlamat(String alamat) {
        this.alamat = alamat;
    }

    
    @Column(name="email", length=100)
    public String getEmail() {
        return this.email;
    }
    
    public void setEmail(String email) {
        this.email = email;
    }

    
    @Column(name="jenis_kelamin")
    public boolean isJenisKelamin() {
        return this.jenisKelamin;
    }
    
    public void setJenisKelamin(boolean jenisKelamin) {
        this.jenisKelamin = jenisKelamin;
    }

    
    @Column(name="nama", length=100)
    public String getNama() {
        return this.nama;
    }
    
    public void setNama(String nama) {
        this.nama = nama;
    }

    
    @Column(name="no_telepon", length=20)
    public String getNoTelepon() {
        return this.noTelepon;
    }
    
    public void setNoTelepon(String noTelepon) {
        this.noTelepon = noTelepon;
    }

    
    @Column(name="password", length=200)
    public String getPassword() {
        return this.password;
    }
    
    public void setPassword(String password) {
        this.password = password;
    }

    
    @Column(name="status_aktif")
    public boolean isStatusAktif() {
        return this.statusAktif;
    }
    
    public void setStatusAktif(boolean statusAktif) {
        this.statusAktif = statusAktif;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="tanggal_keluar", length=19)
    public Date getTanggalKeluar() {
        return this.tanggalKeluar;
    }
    
    public void setTanggalKeluar(Date tanggalKeluar) {
        this.tanggalKeluar = tanggalKeluar;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="tanggal_masuk", length=19)
    public Date getTanggalMasuk() {
        return this.tanggalMasuk;
    }
    
    public void setTanggalMasuk(Date tanggalMasuk) {
        this.tanggalMasuk = tanggalMasuk;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="petugas")
    public Set<Transaksi> getTransaksis() {
        return this.transaksis;
    }
    
    public void setTransaksis(Set<Transaksi> transaksis) {
        this.transaksis = transaksis;
    }




}


