package edu.amikom.perpus.domain;
// Generated May 19, 2019 11:22:43 PM by Hibernate Tools 4.3.1

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Transaksi generated by hbm2java
 */
@Entity
@Table(name = "transaksi")
public class Transaksi implements java.io.Serializable {

    private Integer idTansaksi;
    private Mahasiswa mahasiswa;
    private Petugas petugas;
    private Date tanggalKembali;
    private Date tanggalPinjam;
    private Set<DetailTransaksi> detailTransaksis = new HashSet<DetailTransaksi>(0);

    public Transaksi() {
    }

    public Transaksi(Mahasiswa mahasiswa, Petugas petugas, Date tanggalKembali, Date tanggalPinjam) {
        this.mahasiswa = mahasiswa;
        this.petugas = petugas;
        this.tanggalKembali = tanggalKembali;
        this.tanggalPinjam = tanggalPinjam;
    }

    public Transaksi(Mahasiswa mahasiswa, Petugas petugas, Date tanggalKembali, Date tanggalPinjam, Set<DetailTransaksi> detailTransaksis) {
        this.mahasiswa = mahasiswa;
        this.petugas = petugas;
        this.tanggalKembali = tanggalKembali;
        this.tanggalPinjam = tanggalPinjam;
        this.detailTransaksis = detailTransaksis;
    }

    @Id
    @GeneratedValue(strategy = IDENTITY)

    @Column(name = "id_tansaksi", unique = true)
    public Integer getIdTansaksi() {
        return this.idTansaksi;
    }

    public void setIdTansaksi(Integer idTansaksi) {
        this.idTansaksi = idTansaksi;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "nim")
    public Mahasiswa getMahasiswa() {
        return this.mahasiswa;
    }

    public void setMahasiswa(Mahasiswa mahasiswa) {
        this.mahasiswa = mahasiswa;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "nip")
    public Petugas getPetugas() {
        return this.petugas;
    }

    public void setPetugas(Petugas petugas) {
        this.petugas = petugas;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name = "tanggal_kembali", length = 19)
    public Date getTanggalKembali() {
        return this.tanggalKembali;
    }

    public void setTanggalKembali(Date tanggalKembali) {
        this.tanggalKembali = tanggalKembali;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name = "tanggal_pinjam", length = 19)
    public Date getTanggalPinjam() {
        return this.tanggalPinjam;
    }

    public void setTanggalPinjam(Date tanggalPinjam) {
        this.tanggalPinjam = tanggalPinjam;
    }

    @OneToMany(fetch = FetchType.LAZY, mappedBy = "transaksi")
    public Set<DetailTransaksi> getDetailTransaksis() {
        return this.detailTransaksis;
    }

    public void setDetailTransaksis(Set<DetailTransaksi> detailTransaksis) {
        this.detailTransaksis = detailTransaksis;
    }

}
